apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - priority-classes.yaml
  - apps-metadata-server-deployment.yaml
  - apps-metadata-server-service.yaml
  - config-notification-server-configmap.yaml
  - config-notification-server-deployment.yaml
  - config-notification-server-service.yaml
  - config-server-configmap.yaml
  - config-server-deployment.yaml
  - config-server-service.yaml
  - gridcapa-gateway-configmap.yaml
  - gridcapa-gateway-deployment.yaml
  - gridcapa-gateway-service.yaml
  - gridcapa-interruption-server-configmap.yaml
  - gridcapa-interruption-server-deployment.yaml
  - gridcapa-interruption-server-service.yaml
  - gridcapa-rao-runner-configmap.yaml
  - gridcapa-rao-runner-deployment.yaml
  - gridcapa-rao-runner-service.yaml
  - gridcapa-rao-failure-handler-configmap.yaml
  - gridcapa-rao-failure-handler-deployment.yaml
  - gridcapa-rao-failure-handler-service.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - rabbitmq-configmap.yaml
  - rabbitmq-service.yaml
  - rabbitmq-statefulset.yaml
  - minio-get-storage-data-cron.yaml

configMapGenerator:
  - name: homepage-configmap
    files:
      - homepage.html=homepage/homepage.html
      - homepage.css=homepage/homepage.css
      - homepage.js=homepage/homepage.js
      - farao-logo.svg=homepage/farao-logo.svg