spring:
  application:
    name: core-valid-day-ahead-conservative-post-processing
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: gridcapa
    password: gridcapa
    template:
      reply-timeout: 7200000
  cloud:
    stream:
      default:
        group: core-valid-day-ahead-conservative-post-processing
      bindings:
        consumeTaskDtoUpdate-in-0:
          destination: core-valid-day-ahead-conservative-task-updated
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
        bindings:
          consumeTaskDtoUpdate-in-0:
            consumer:
              binding-routing-key: status

logback:
  amqp:
    exchange: core-valid-day-ahead-conservative-task-manager-logs-exchange
    routing-key: "#"

core-valid-d2-post-processing:
  url:
    task-manager-timestamp-url: http://core-valid-day-ahead-conservative-task-manager:8080/tasks/
    task-manager-business-date-url: http://core-valid-day-ahead-conservative-task-manager:8080/tasks/businessdate/

minio-adapter:
  bucket: gridcapa
  base-path: /CORE/VALID/D2CC_CONSERVATIVE
  access-key: gridcapa
  secret-key: gridcapa
  url: http://minio:9000
