data-bridge:
  configuration:
    zone-id: "Europe/Paris"
    target-process: CORE_VALID
    files:
      - file-type: CGM
        file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})_(?<hour>[0-9]{2})(?<minute>[0-9]{2}).*.(uct|UCT)"
        time-validity: hourly
        remote-file-regex: ".*"
        source-directory: "/cgms"
        sink-directory: "/CGMs"
        file-list-persistence-file: /tmp/gridcapa/ftp-metadata-store.cgm.properties
      - file-type: CNEC-RAM
        file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-3]{1}[0-9]{1})-(?<hour>[0-2]{1}[0-9]{1})00-F309-INTERM_AMRINCL_REFBAL_PRES_FBPARAMS_CSV-v(?<version>[0-9]*).(csv|CSV)"
        time-validity: hourly
        remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F309-v(?<version>[0-9]*)-17XTSO-CS------W-to-10V1001C--00085T.(zip|ZIP)"
        doUnzip: true
        source-directory: "/cnecrams"
        sink-directory: "/CNECRAMs"
        file-list-persistence-file: /tmp/gridcapa/ftp-metadata-store.cnecram.properties
      - file-type: GLSK
        file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F226-.*.(xml|XML)"
        time-validity: daily
        remote-file-regex: ".*"
        source-directory: "/glsks"
        sink-directory: "/GLSKs"
        file-list-persistence-file: /tmp/gridcapa/ftp-metadata-store.glsk.properties
      - file-type: MARKET-POINT
        file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-FID2-632-v(?<version>[0-9]*)-10V1001C--00264T-to-10V1001C-00085T.(xml|XML)"
        time-validity: daily
        remote-file-regex: ".*"
        source-directory: "/marketpoints"
        sink-directory: "/MARKETPOINTs"
        file-list-persistence-file: /tmp/gridcapa/ftp-metadata-store.marketpoint.properties
      - file-type: MERGED-CNEC
        file-regex: ".*"
        time-validity: hourly
        remote-file-regex: ".*"
        source-directory: "/mergedcnecs"
        sink-directory: "/MERGEDCNECs"
        file-list-persistence-file: /tmp/gridcapa/ftp-metadata-store.mergedcnec.properties
      - file-type: PRA
        file-regex: ".*"
        time-validity: hourly
        remote-file-regex: ".*"
        source-directory: "/pras"
        sink-directory: "/PRAs"
        file-list-persistence-file: /tmp/gridcapa/ftp-metadata-store.pra.properties
      - file-type: VERTICES
        file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-3]{1}[0-9]{1})-(?<hour>[0-2]{1}[0-9]{1})(?<minute>00)[abAB]{0,1}-FID2-701-INIT_VIRG_REFBAL_PRES_REPREVERTICES-v(?<version>[0-9]*).(csv|CSV)"
        time-validity: hourly
        remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-FID2-645-v(?<version>[0-9]*)-10V1001C--00264T-to-10V1001C-00085T.(zip|ZIP)"
        doUnzip: true
        source-directory: "/vertices"
        sink-directory: "/VERTICEs"
        file-list-persistence-file: /tmp/gridcapa/ftp-metadata-store.vertices.properties
  sources:
    ftp:
      active: true
      host: ftp-server
      port: 21
      username: gridcapa
      password: gridcapa
      base-directory: /data/gridcapa/core/valid/d2cc-conservative
      polling-delay-in-ms: 5000
      max-messages-per-poll: 10
      max-pool-size: 2
      timeouts:
        data-timeout: 60000
        default-timeout: 500
        connect-timeout: 1000
        session-wait-timeout: 1000
  sinks:
    minio:
      url: http://minio:9000
      access-key: gridcapa
      secret-key: gridcapa
      bucket: gridcapa
      base-directory: /CORE/VALID/D2CC_CONSERVATIVE
