spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: gridcapa
    password: gridcapa
    template:
      reply-timeout: 6000000
  cloud:
    stream:
      default:
        binder: rabbit
        group: core-valid-day-ahead-conservative-adapter
      bindings:
        consumeTask-in-0:
          destination: core-valid-day-ahead-conservative-run-task
        consumeAutoTask-in-0:
          destination: core-valid-day-ahead-conservative-run-task-auto
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1

core-valid-day-ahead-conservative-runner:
  binding:
    destination: core-valid-day-ahead-conservative-requests

minio-adapter:
  bucket: gridcapa
  base-path: /CORE/VALID/D2CC_CONSERVATIVE
  access-key: gridcapa
  secret-key: gridcapa
  url: http://minio:9000

core-valid-day-ahead-conservative-adapter:
  whitelist:
    - http://minio:9000/