apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ce-cc-data-bridge-storage
  labels:
    app: gridcapa
    component: data-bridge-storage
    region: ce
    process: cc
spec:
  storageClassName: azure-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 96M
