kind: ConfigMap
apiVersion: v1
metadata:
  name: ce-cc-post-processing-configmap
  labels:
    app: gridcapa
    component: runner
    region: ce
    process: cc
data:
  application.yml: |-
    spring:
      application:
        name: ce-cc-gridcapa-post-processing
      rabbitmq:
        host: gridcapa-rabbitmq
        username: ${RABBITMQ_USER}
        password: ${RABBITMQ_PASSWORD}
        port: 5672
        template:
          reply-timeout: 7200000
      cloud:
        stream:
          default:
            group: ce-cc-post-processing
          bindings:
            consumeTaskDtoUpdate-in-0:
              destination: ce-cc-task-updated
          rabbit:
            default:
              consumer:
                auto-bind-dlq: true
                max-attempts: 1
            bindings:
              consumeTaskDtoUpdate-in-0:
                consumer:
                  binding-routing-key: status

    logback:
      amqp:
        exchange: ce-cc-task-manager-logs-exchange
        routing-key: "#"
    
    ce-cc-post-processing:
      url:
        task-manager-timestamp-url: http://ce-cc-task-manager/tasks/
        task-manager-business-date-url: http://ce-cc-task-manager/tasks/businessdate/

    minio-adapter:
      bucket: gridcapa
      base-path: /CE/CC
      access-key: ${GRIDCAPA_MINIO_USER}
      secret-key: ${GRIDCAPA_MINIO_PASSWORD}
      url: http://gridcapa-minio:9000/