kind: Deployment
apiVersion: apps/v1
metadata:
  name: ce-cc-output-data-bridge
  labels:
    app: gridcapa
    component: data-bridge
    file: output
    region: ce
    process: cc

spec:
  selector:
    matchLabels:
      app: gridcapa
      component: data-bridge
      file: output
      region: ce
      process: cc
  template:
    metadata:
      labels:
        app: gridcapa
        component: data-bridge
        file: output
        region: ce
        process: cc
    spec:
      containers:
        - name: ce-cc-output-data-bridge
          image: gridcapa-ce-cc-output-data-bridge
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OUTPUT_HOST
              valueFrom:
                secretKeyRef:
                  name: gridcapa-ftp-credentials
                  key: ftp-host
            - name: OUTPUT_PORT
              valueFrom:
                secretKeyRef:
                  name: gridcapa-ftp-credentials
                  key: ftp-port
            - name: OUTPUT_USER
              valueFrom:
                secretKeyRef:
                  name: gridcapa-ftp-credentials
                  key: ftp-user
            - name: OUTPUT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gridcapa-ftp-credentials
                  key: ftp-password
            - name: OUTPUT_BASE_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: GRIDCAPA_SINK_DIRECTORY_CE_CC
            - name: OUTPUT_POLLING_DELAY
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: GRIDCAPA_OUTPUT_POLLING_DELAY_CE_CC
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gridcapa-minio-credentials
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gridcapa-minio-credentials
                  key: minio-secret-key
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: GRIDCAPA_MINIO_BUCKET_CE_CC
            - name: MINIO_BASE_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: GRIDCAPA_MINIO_BASE_DIRECTORY_OUTPUT_CE_CC
          volumeMounts:
            - mountPath: /config/application.yml
              subPath: application.yml
              name: ce-cc-output-data-bridge-configmap-volume
            - mountPath: /data/gridcapa
              name: ce-cc-output-data-bridge-data
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 35
            timeoutSeconds: 2
            periodSeconds: 600
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            timeoutSeconds: 2
            periodSeconds: 600
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              cpu: "0.5"
              memory: "2Gi"
            limits:
              cpu: "1.0"
              memory: "2Gi"
      restartPolicy: Always
      volumes:
        - name: ce-cc-output-data-bridge-configmap-volume
          configMap:
            name: ce-cc-output-data-bridge-configmap
        - name: ce-cc-output-data-bridge-data
          persistentVolumeClaim:
            claimName: ce-cc-data-bridge-storage
