kind: ConfigMap
apiVersion: v1
metadata:
  name: ce-cc-app-process-metadata-configmap
  labels:
    app: gridcapa
    component: front-app-process-metadata
    region: ce
    process: cc
data:
  process-metadata.json: |-
    {
      "processName": "CE Capacity Calculation",
      "globalViewTimestampFilter": [
      ],
      "manualExportEnabled": false,
      "parametersEnabled": true,
      "eventLevelPredefinedFilter": [
        {
          "filterName": "INFO",
          "defaultChecked": false,
          "filterValue": [
            "INFO"
          ]
        },
        {
          "filterName": "WARN",
          "defaultChecked": false,
          "filterValue": [
            "WARN"
          ]
        },
        {
          "filterName": "ERROR",
          "defaultChecked": false,
          "filterValue": [
            "ERROR"
          ]
        }
      ],
      "eventLogPredefinedFilter": [
      ]
    }
