apiVersion: v1
kind: Service
metadata:
  name: ce-cc-task-manager
  labels:
    app: gridcapa
    component: task-manager
    region: ce
    process: cc
spec:
  type: ClusterIP
  selector:
    app: gridcapa
    component: task-manager
    region: ce
    process: cc
  ports:
    - port: 80
      targetPort: 8080
      name: http
