kind: Deployment
apiVersion: apps/v1
metadata:
  name: ce-cc-task-manager
  labels:
    app: gridcapa
    component: task-manager
    region: ce
    process: cc
spec:
  selector:
    matchLabels:
      app: gridcapa
      component: task-manager
      region: ce
      process: cc
  template:
    metadata:
      labels:
        app: gridcapa
        component: task-manager
        region: ce
        process: cc
    spec:
      priorityClassName: medium-priority
      containers:
        - name: ce-cc-task-manager
          image: gridcapa-ce-cc-task-manager
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: GRIDCAPA_APP_URL
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: GRIDCAPA_POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: GRIDCAPA_POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: GRIDCAPA_POSTGRES_CE_CC_DB
            - name: POSTGRES_SSL_MODE
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: GRIDCAPA_POSTGRES_SSL_MODE_CE_CC
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: gridcapa-postgresql-credentials
                  key: ce-cc-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gridcapa-postgresql-credentials
                  key: ce-cc-password
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gridcapa-minio-credentials
                  key: minio-access-key
            - name: MINIO_BASE_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: GRIDCAPA_MINIO_BASE_DIRECTORY_CE_CC
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gridcapa-minio-credentials
                  key: minio-secret-key
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: gridcapa-rabbitmq-credentials
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gridcapa-rabbitmq-credentials
                  key: rabbitmq-password
          volumeMounts:
            - mountPath: /config/application.yml
              subPath: application.yml
              name: ce-cc-task-manager-configmap-volume
            - mountPath: /config/data.sql
              subPath: data.sql
              name: ce-cc-task-manager-configmap-volume
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 35
            timeoutSeconds: 2
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              cpu: "1.0"
              memory: "5Gi"
            limits:
              cpu: "4.0"
              memory: "10Gi"
      initContainers:
        - name: minio-notifications
          image: minio-mc
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gridcapa-minio-credentials
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gridcapa-minio-credentials
                  key: minio-secret-key
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: GRIDCAPA_MINIO_BUCKET_CE_CC
          command: ['/bin/sh', "-c","mc alias set gridcapa http://gridcapa-minio:9000 $(MINIO_ACCESS_KEY) $(MINIO_SECRET_KEY) && (mc event add gridcapa/$(MINIO_BUCKET) arn:minio:sqs::_:amqp --event put,delete || true)"]
      restartPolicy: Always
      volumes:
        - name: ce-cc-task-manager-configmap-volume
          configMap:
            name: ce-cc-task-manager-configmap
