kind: ConfigMap
apiVersion: v1
metadata:
  name: ce-cc-data-bridge-configmap
  labels:
    app: gridcapa
    component: data-bridge
    region: ce
    process: cc
data:
  application.yml: |-
    data-bridge:
      configuration:
        zone-id: "Europe/Paris"
        target-process: CE_CC
        files:
          - file-type: CBCORA
            file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F301-.*CORESO.*\.xml
            remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F301-.*CORESO.*\\.xml"
            source-directory: "/F301"
            sink-directory: "/CRACs"
            file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.cbcora.properties
          - file-type: CGM
            file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F119-.*CORESO.*\.zip
            remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F119-.*CORESO.*\\.zip"
            do-unzip: false
            source-directory: "/F119"
            sink-directory: "/CGMs"
            file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.cgm.properties
          - file-type: GLSK
            file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F319-.*CORESO.*\.xml
            remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F319-.*CORESO.*\\.xml"
            source-directory: "/F319"
            sink-directory: "/GLSKs"
            file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.glsk.properties
          - file-type: RAOREQUEST
            file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F302-.*CORESO.*\.xml
            remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F302-.*CORESO.*\\.xml"
            source-directory: "/F302"
            sink-directory: "/RAOREQUESTs"
            file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.raorequest.properties
          - file-type: REFPROG
            file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F120-.*CORESO.*\.xml
            remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F120-.*CORESO.*\\.xml"
            source-directory: "/F120"
            sink-directory: "/REFPROGs"
            file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.refprog.properties
          - file-type: VIRTUALHUB
            file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F327-.*CORESO.*\.xml
            remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})(?:-F327-.*CORESO)?.*\\.xml"
            source-directory: "/F327"
            sink-directory: "/VIRTUALHUBs"
            file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.virtualhub.properties
          - file-type: DCCGM
            file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F139-v(?<version>[0-9]+)-.*CORESO.*\.zip
            remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F139-v(?<version>[0-9]+)-.*CORESO.*\\.zip"
            do-unzip: false
            source-directory: "/F139"
            sink-directory: "/DCCGMs"
            file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.dccgm.properties
      sources:
        ftp:
          active: true
          host: ${SOURCE_HOST}
          port: ${SOURCE_PORT}
          username: ${SOURCE_USER}
          password: ${SOURCE_PASSWORD}
          base-directory: ${SOURCE_BASE_DIRECTORY}
          polling-delay-in-ms: ${POLLING_DELAY}
          max-messages-per-poll: ${MAX_POLLED_FILES}
          max-pool-size: ${MAX_POOL_SIZE}
          timeouts:
            data-timeout: ${DATA_TIMEOUT}
            default-timeout: ${DEFAULT_TIMEOUT}
            connect-timeout: ${CONNECTION_TIMEOUT}
            session-wait-timeout: ${SESSION_WAIT_TIMEOUT}
      sinks:
        minio:
          url: http://gridcapa-minio:9000
          access-key: ${MINIO_ACCESS_KEY}
          secret-key: ${MINIO_SECRET_KEY}
          bucket: ${MINIO_BUCKET}
          base-directory: ${MINIO_BASE_DIRECTORY}
