kind: ConfigMap
apiVersion: v1
metadata:
  name: ce-cc-runner-configmap
  labels:
    app: gridcapa
    component: runner
    region: ce
    process: cc
data:
  application.yml: |-
    spring:
      rabbitmq:
        host: gridcapa-rabbitmq
        port: 5672
        username: ${RABBITMQ_USER}
        password: ${RABBITMQ_PASSWORD}
        template:
          reply-timeout: 7200000
      cloud:
        stream:
          default:
            binder: rabbit
            group: ce-cc-runner
          bindings:
            task-status-update:
              destination: ce-cc-task-status-updated
            request-in-0:
              destination: ce-cc-requests

    logback:
      amqp:
        exchange: ce-cc-task-manager-logs-exchange
        routing-key: "#"
    
    rao-runner-server:
      amqp:
        client-app-id: ce-cc-runner
        queue-name: rao-request-queue

    core-cc-runner:
      async-time-out: 7200000
      whitelist:
        - http://gridcapa-minio:9000/

    minio-adapter:
      bucket: gridcapa
      base-path: /CE/CC
      access-key: ${GRIDCAPA_MINIO_USER}
      secret-key: ${GRIDCAPA_MINIO_PASSWORD}
      url: http://gridcapa-minio:9000/