apiVersion: v1
kind: Service
metadata:
  name: ce-cc-rao-logs-dispatcher
  labels:
    app: gridcapa
    component: rao-logs-dispatcher
    region: ce
    process: cc
spec:
  type: ClusterIP
  selector:
    app: gridcapa
    component: rao-logs-dispatcher
    region: ce
    process: cc
  ports:
    - port: 80
      targetPort: 8080
      name: http
