data-bridge:
  configuration:
    zone-id: "Europe/Paris"
    target-process: CE_CC
    files:
      - file-type: CBCORA
        file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F301-.*CORESO.*\.xml
        remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F301-.*CORESO.*\\.xml"
        source-directory: "/cracs"
        sink-directory: "/CRACs"
        file-list-persistence-file: /tmp/gridcapa/ce-cc/ftp-metadata-store.crac.properties
      - file-type: CGM
        file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F119-.*CORESO.*\.zip
        remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F119-.*CORESO.*\\.zip"
        do-unzip: false
        source-directory: "/cgms"
        sink-directory: "/CGMs"
        file-list-persistence-file: /tmp/gridcapa/ce-cc/ftp-metadata-store.cgm.properties
      - file-type: GLSK
        file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F319-.*CORESO.*\.xml
        remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F319-.*CORESO.*\\.xml"
        source-directory: "/glsks"
        sink-directory: "/GLSKs"
        file-list-persistence-file: /tmp/gridcapa/ce-cc/ftp-metadata-store.glsk.properties
      - file-type: RAOREQUEST
        file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F302-.*CORESO.*\.xml
        remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F302-.*CORESO.*\\.xml"
        source-directory: "/raorequests"
        sink-directory: "/RAOREQUESTs"
        file-list-persistence-file: /tmp/gridcapa/ce-cc/ftp-metadata-store.raorequest.properties
      - file-type: REFPROG
        file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F120-.*CORESO.*\.xml
        remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F120-.*CORESO.*\\.xml"
        source-directory: "/refprogs"
        sink-directory: "/REFPROGs"
        file-list-persistence-file: /tmp/gridcapa/ce-cc/ftp-metadata-store.refprog.properties
      - file-type: VIRTUALHUB
        file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F327-.*CORESO.*\.xml
        remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})(?:-F327-.*CORESO)?.*\\.xml"
        source-directory: "/virtualhubs"
        sink-directory: "/VIRTUALHUBs"
        file-list-persistence-file: /tmp/gridcapa/ce-cc/ftp-metadata-store.virtualhub.properties
      - file-type: DCCGM
        file-regex: (?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F139-v(?<version>[0-9]+)-.*CORESO.*\.zip
        remote-file-regex: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})-F139-v(?<version>[0-9]+)-.*CORESO.*\\.zip"
        do-unzip: false
        source-directory: "/F139"
        sink-directory: "/DCCGMs"
        file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.dccgm.properties
        ################# OLD version file names
      - file-type: CBCORA
        file-regex: .*CORESO-F301_F301-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\.xml
        remote-file-regex: ".*CORESO-F301_F301-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\\.xml"
        source-directory: "/cracs"
        sink-directory: "/CRACs"
        file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.cbcora.properties
      - file-type: CGM
        file-regex: .*CORESO-F119_F119-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\.zip
        remote-file-regex: ".*CORESO-F119_F119-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\\.zip"
        do-unzip: false
        source-directory: "/cgms"
        sink-directory: "/CGMs"
        file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.cgm.properties
      - file-type: GLSK
        file-regex: .*CORESO-F319_F319-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\.xml
        remote-file-regex: ".*CORESO-F319_F319-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\\.xml"
        source-directory: "/glsks"
        sink-directory: "/GLSKs"
        file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.glsk.properties
      - file-type: RAOREQUEST
        file-regex: .*CORESO-F302_F302-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\.xml
        remote-file-regex: ".*CORESO-F302_F302-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\\.xml"
        source-directory: "/raorequests"
        sink-directory: "/RAOREQUESTs"
        file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.raorequest.properties
      - file-type: REFPROG
        file-regex: .*CORESO-F120_F120-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\.xml
        remote-file-regex: ".*CORESO-F120_F120-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\\.xml"
        source-directory: "/refprogs"
        sink-directory: "/REFPROGs"
        file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.refprog.properties
      - file-type: VIRTUALHUB
        file-regex: .*CORESO-F327_F327-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\.xml
        remote-file-regex: ".*CORESO-F327_F327-(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2}).*\\.xml"
        source-directory: "/virtualhubs"
        sink-directory: "/VIRTUALHUBs"
        file-list-persistence-file: /data/gridcapa/ce-cc/ftp-metadata-store.virtualhub.properties
  sources:
    ftp:
      active: true
      host: ftp-server
      port: 21
      username: gridcapa
      password: gridcapa
      base-directory: /data/gridcapa/ce/cc
      polling-delay-in-ms: 5000
      max-messages-per-poll: 10
      max-pool-size: 2
      timeouts:
        data-timeout: 60000
        default-timeout: 500
        connect-timeout: 1000
        session-wait-timeout: 1000
  sinks:
    minio:
      url: http://minio:9000
      access-key: gridcapa
      secret-key: gridcapa
      bucket: gridcapa
      base-directory: /CE/CC